### ISSUE TITLE
[ISSUE]: Browser error

### ISSUE THREAD

**Issue by 0RadicalLarry0** [deiteris/voice-changer#167] opened 2024-08-11 11:46 UTC
### Voice Changer Version

Latest as of Aug 11, 2024

### Operational System

Windows 10

### GPU

AMD Radeon 5700 XT

### Read carefully and check the options

- [ ] I've tried to Clear Settings
- [ ] Sample/Default Models are working
- [ ] I've tried to change the Chunk Size
- [ ] GUI was successfully launched
- [X] I've read the [tutorial](https://github.com/w-okada/voice-changer/blob/master/tutorials/tutorial_rvc_en_latest.md)
- [X] I've tried to extract to another folder (or re-extract) the .zip file

### Model Type

RVC

### Issue Description

Browser GUI does not work. Tried to use on Edge and Firefox.

Happens on directml and nvidia versions.

There are no errors in cmd window.

### Application Screenshot

Firefox:
![Screenshot_1125](https://github.com/user-attachments/assets/7eff7887-d219-4803-9e86-44f9ef1800c3)

Edge:
![Screenshot_1126](https://github.com/user-attachments/assets/898470cf-fdc6-478a-91b3-2bf03a0e1bea)

### Logs on console

```
D:\Program Files\AI\voice-changer-nvidia>"D:\Program Files\AI\voice-changer-nvidia\zluda\zluda.exe" -- "D:\Program Files\AI\voice-changer-nvidia\voice-changer-windows-amd64-cuda\MMVCServerSIO\MMVCServerSIO.exe" --launch-browser False
2024-08-11 06:45:14,709 INFO     [main] Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
2024-08-11 06:45:14,710 INFO     [main] Voice changer version: b2277 NVIDIA-CUDA
2024-08-11 06:45:14,710 INFO     [WeightDownloader] Loading weights.
2024-08-11 06:45:14,924 INFO     [Downloader] Verified pretrain/crepe_onnx_full.onnx
2024-08-11 06:45:14,934 INFO     [Downloader] Verified pretrain/crepe_onnx_tiny.onnx
2024-08-11 06:45:14,951 INFO     [Downloader] Verified pretrain/crepe_full.pth
2024-08-11 06:45:14,959 INFO     [Downloader] Verified pretrain/crepe_tiny.pth
2024-08-11 06:45:15,015 INFO     [Downloader] Verified pretrain/content_vec_500.onnx
2024-08-11 06:45:15,045 INFO     [Downloader] Verified pretrain/rmvpe.pt
2024-08-11 06:45:15,098 INFO     [Downloader] Verified pretrain/rmvpe.onnx
2024-08-11 06:45:15,111 INFO     [Downloader] Verified pretrain/fcpe.pt
2024-08-11 06:45:15,123 INFO     [Downloader] Verified pretrain/fcpe.onnx
2024-08-11 06:45:15,123 INFO     [WeightDownloader] All weights are loaded!
2024-08-11 06:45:15,124 INFO     [main] protocol: HTTP
Open error: is JACK server running?
numpy\core\getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
numpy\core\getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
numpy\core\getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
numpy\core\getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
2024-08-11 06:45:17,336 INFO     [loader] Loading faiss with AVX2 support.
2024-08-11 06:45:17,351 INFO     [loader] Successfully loaded faiss with AVX2 support.
2024-08-11 06:45:17,814 INFO     [VoiceChangerManager] Initializing...
2024-08-11 06:45:17,846 INFO     [DeviceManager] Initialized DeviceManager. Backend statuses:
2024-08-11 06:45:17,846 INFO     [DeviceManager] * DirectML: False, device count: 0
2024-08-11 06:45:17,846 INFO     [DeviceManager] * CUDA: True, device count: 1
2024-08-11 06:45:17,846 INFO     [DeviceManager] * MPS: False
2024-08-11 06:45:17,860 INFO     [DeviceManager] Switched to CPU (cpu). FP16 support: False
2024-08-11 06:45:17,861 INFO     [VoiceChangerManager] Initialized.
2024-08-11 06:45:17,861 ERROR    [VoiceChangerManager] Unknown voice changer model: None
2024-08-11 06:45:17,861 INFO     [MMVC_Rest] Initializing...
2024-08-11 06:45:17,875 INFO     [MMVC_Rest] Initialized.
2024-08-11 06:45:17,876 INFO     [MMVC_SocketIOApp] Initializing...
2024-08-11 06:45:17,876 INFO     [MMVC_SocketIOApp] Initialized.
2024-08-11 06:45:18,157 INFO     [main] --------
2024-08-11 06:45:18,157 INFO     [main] The server is listening on http://127.0.0.1:18888/
2024-08-11 06:45:18,157 INFO     [main] --------
```

**Comment by deiteris** [comment] 2024-08-11 13:12
Hi @0RadicalLarry0! Looks like there is a similar issue with original version as well: https://github.com/w-okada/voice-changer/issues/510.

Are you using JACK Audio Connection Kit by chance? What are the audio devices that you have?

Also, if possible, open browser's developer tools > **Console**, navigate to the browser GUI and show a screenshot with error here. It seems like a problem when listing audio devices or there's some other underlying error, but I'd need to reproduce it somehow.

Just in case, Edge 127.0.2651.98 (current latest) has no problems listing devices:
![image](https://github.com/user-attachments/assets/c09d6599-060e-45f9-9daf-faa44f79f6a5)

Firefox 128.0.2 also works without issues:
![image](https://github.com/user-attachments/assets/a4cd4bcb-7284-4472-a218-55a500f87de6)

**Comment by 0RadicalLarry0** [comment] 2024-08-11 16:04
The cause of the error on edge was a browser extension.
https://microsoftedge.microsoft.com/addons/detail/trace-online-tracking-p/fhjjfbdhmjpcdckdoglijoahcdhndeco

As for firefox, I don't know. I don't have any extensions installed for firefox.
![Screenshot_1127](https://github.com/user-attachments/assets/fc5cdf86-3aaf-4198-8a77-7bbc772e03da)
![Screenshot_1128](https://github.com/user-attachments/assets/e917ec8a-fc83-4f4d-8b68-7c09d20a1d74)

Since the issue is resolved for me on edge, I'm satisfied. Let me know if you need more info to figure out what's wrong with my firefox though.

**Comment by 0RadicalLarry0** [comment] 2024-08-11 16:07
Also, I do have Jack Audio Connection Kit but I'm not using it. It's never caused problems with w-okada and mainline rvc voicechangers.

**Comment by deiteris** [comment] 2024-08-11 17:22
Could you check Browser privacy settings in Firefox? It might be that you have all cookies blocked and this causes `Error: No available storage method found.` error. I managed to reproduce this on my end:
![image](https://github.com/user-attachments/assets/8b2740d5-6cec-4417-91b2-780f31f0360d)

**Comment by 0RadicalLarry0** [comment] 2024-08-11 17:38
I only had it on strict and changing it to standard didn't fix it. What did fix it though was updating firefox. Silly problems with simple solutions!

In my defense, I don't use firefox as my main browser.

**Comment by deiteris** [comment] 2024-08-11 18:43
Glad it worked after all 😄 I'll keep in mind that tracker blockers can cause issues and try to look for a workaround maybe. Closing this.

**Closed as completed by deiteris** 2024-08-11 18:43 UTC
